# TODO: Remove this. This is just here to get around a corporate firewall but shouldn't stay in the config.
enableStrictSsl: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
